public with sharing class Constants {

    public static final String STATUS_AVAILABLE = 'Available';
    public static final String STATUS_NOT_AVAILABLE = 'Not Available';
    public static final String STATUS_AT_SERVICE = 'At Service';
    public static final String VALIDATE_DATE_ERROR = 'Next maintenance date should be after the last.';
    public static final String STATUS_MESSAGE = 'Currently this vehicle is not available: plate number {0} model {1}';
}
